### ISSUE TITLE
ハンズオンとオフィスアワーを登録する

### ISSUE THREAD

**Issue by mi-bear** [GoCon/2021-Spring#32]
Ref: https://goconjp.slack.com/archives/GPU5HCWE4/p1617282751247000

## 案1 Column を2つ
<img width="1361" alt="ハンズオンとオフィスアワーの登録-1" src="https://user-images.githubusercontent.com/7250468/113501956-05b5c980-9564-11eb-8090-e794af75ad4d.png">

## 案2 Column を1つ
<img width="1361" alt="ハンズオンとオフィスアワーの登録-2" src="https://user-images.githubusercontent.com/7250468/113501960-0d756e00-9564-11eb-84b0-acf412a5c6e5.png">

#### (1-1) Title
ハンズオンタイトルを表示します。
ハンズオンは2種類を予定しています。

1. 数で遊ぼう 〜 コマンドラインツールで数を操る
2. 実況！Gopher あみぐるみ (仮)

#### (1-2) Speaker
通常のスピーカーと同じように登録します。

```
---
key: wwgt
name: Women Who Go Tokyo
id: wwgt
feature: false
photoURL: /images/speakers/speaker-wwgt.jpg
socials:
- icon: twitter
  link: 'https://twitter.com/wwg_tokyo'
  name: wwg_tokyo
- icon: link
  link: 'https://web.womenwhogo.tokyo'
  name: website  
---
Women Who Go Tokyo は、サンフランシスコ発祥の女性とジェンダーマイノリティの人々があつまる Go 言語のコミュニティである Women Who Go の東京支部です。
```

#### (1-3) セッションのレベル
通常セッションのときも all 以外で表示されている、電波の強さアイコンのことです。
タグは表示しなくても良いのですが、可能であれば、表示できたら良いなぁと思っております。(タグは必要ありませんが、あったほうが良ければ考えます！)

#### (1-4) リンク先
https://gocon.jp/speakers/wwgt に遷移します。

#### (2-1) 企業ロゴ
Goルドスポンサー、シルバースポンサーの企業ロゴを表示しますが、一部オフィスアワーは設けられない、という企業様もいらっしゃるようなので、スポンサーのプランで強制的に表示するよりは、スポンサー (partner) を指定して表示できるほうが良いです。
